export enum CONTAINER {
  POSTGRES = 'postgresdb',
  KEYCLOAK = 'keycloak-app',
  IAMKC_SVC = 'onecx-iam-kc-svc',
  PARAMETER_SVC = 'onecx-parameter-svc',
  WORKSPACE_SVC = 'onecx-workspace-svc',
  USER_PROFILE_SVC = 'onecx-user-profile-svc',
  THEME_SVC = 'onecx-theme-svc',
  TENANT_SVC = 'onecx-tenant-svc',
  PRODUCT_STORE_SVC = 'onecx-product-store-svc',
  PERMISSION_SVC = 'onecx-permission-svc',
  PARAMETER_BFF = 'onecx-parameter-bff',
  SHELL_BFF = 'onecx-shell-bff',
  WORKSPACE_BFF = 'onecx-workspace-bff',
  SHELL_UI = 'onecx-shell-ui',
  WORKSPACE_UI = 'onecx-workspace-ui',
  IMPORT_MANAGER = 'importManager',
}
